import { Project, User, Tag, ChatMessage } from '../types/kanban';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-mira',
    name: 'Mira Brown',
    username: '@mira.b',
    email: 'mira.brown@unique.design',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    role: 'Lead Product Designer',
    bio: 'Visual Design, Product Design, Research. Typography & colors lover.',
    badges: ['UX/UI designer', 'Dribbbler'],
    online: true,
  },
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    username: '@alex.r',
    email: 'alex.rivera@unique.design',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    role: 'Design System Architect',
    online: true,
  },
  {
    id: 'user-sarah',
    name: 'Sarah Chen',
    username: '@sarah.c',
    email: 'sarah.chen@unique.design',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    role: 'Senior UI Engineer',
    online: false,
  },
  {
    id: 'user-marcus',
    name: 'Marcus Vance',
    username: '@marcus.v',
    email: 'marcus.vance@unique.design',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    role: 'Frontend Developer',
    online: true,
  },
  {
    id: 'user-elena',
    name: 'Elena Rostova',
    username: '@elena.r',
    email: 'elena.rostova@unique.design',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    role: 'Visual Artist',
    online: false,
  },
];

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag-website', name: 'Website', bgColor: '#E0F2FE', textColor: '#0284C7' }, // Blue
  { id: 'tag-design', name: 'Design', bgColor: '#DCFCE7', textColor: '#16A34A' }, // Green
  { id: 'tag-dribbble', name: 'Dribbble', bgColor: '#FCE7F3', textColor: '#DB2777' }, // Pink
  { id: 'tag-app', name: 'App', bgColor: '#FFEDD5', textColor: '#EA580C' }, // Orange
  { id: 'tag-research', name: 'Research', bgColor: '#FEE2E2', textColor: '#DC2626' }, // Red
  { id: 'tag-frontend', name: 'Frontend', bgColor: '#F3E8FF', textColor: '#9333EA' }, // Purple
  { id: 'tag-planning', name: 'Planning', bgColor: '#E2E8F0', textColor: '#475569' }, // Slate
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: INITIAL_USERS[0], // Mira
    content: "Hi, I have great news. A new project is starting, I'll tell you more about it later.",
    timestamp: '8:29',
    isMe: false,
    type: 'text',
  },
  {
    id: 'msg-2',
    sender: INITIAL_USERS[0],
    content: "It's a new neobank with great deposit terms.",
    timestamp: '8:30',
    isMe: false,
    type: 'text',
  },
  {
    id: 'msg-3',
    sender: INITIAL_USERS[0],
    timestamp: '8:30',
    isMe: false,
    type: 'link',
    linkData: {
      title: 'acorns.com',
      url: 'https://www.acorns.com',
    },
  },
  {
    id: 'msg-4',
    sender: INITIAL_USERS[1],
    content: "Hi. wow, that's intriguing",
    timestamp: '8:30',
    isMe: true,
    type: 'text',
  },
  {
    id: 'msg-5',
    sender: INITIAL_USERS[1],
    content: "I'm looking forward to the details",
    timestamp: '8:30',
    isMe: true,
    type: 'text',
  },
  {
    id: 'msg-6',
    sender: INITIAL_USERS[0],
    timestamp: '8:31',
    isMe: false,
    type: 'meeting',
    meetingData: {
      title: 'MEETING',
      date: 'Jul 28',
      time: '2:20 pm',
    },
  },
  {
    id: 'msg-7',
    sender: INITIAL_USERS[0],
    timestamp: '8:32',
    isMe: false,
    type: 'voice',
    voiceData: {
      duration: '1:42',
    },
  },
  {
    id: 'msg-8',
    sender: INITIAL_USERS[1],
    content: "Okay, I can't wait to get started",
    timestamp: '8:32',
    isMe: true,
    type: 'text',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-unique',
    name: 'Unique',
    key: 'UNQ',
    description: 'Modern product design and engineering workflows for web and mobile.',
    icon: 'Square',
    color: '#3B82F6',
    category: 'all',
    badgeCount: 2,
    subItems: [
      { id: 'sub-web', name: 'Website', checked: true },
      { id: 'sub-ios', name: 'iOS App', checked: true },
      { id: 'sub-dribbble', name: 'Dribbble Shot', checked: true },
    ],
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    columns: [
      { id: 'col-new', title: 'New Request', color: '#EF4444', wipLimit: 10, order: 0 },
      { id: 'col-progress', title: 'In Progress', color: '#64748B', wipLimit: 5, order: 1 },
      { id: 'col-complete', title: 'Complete', color: '#22C55E', order: 2 },
      { id: 'col-approved', title: 'Approved', color: '#94A3B8', order: 3 },
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Pages "About" and "Careers"',
        description: "All the details are in the file, I'm sure it will turn out cool!",
        columnId: 'col-new',
        priority: 'high',
        assignees: [INITIAL_USERS[0]],
        tags: [INITIAL_TAGS[0], INITIAL_TAGS[1]], // Website, Design
        subtasks: [
          { id: 'st-1', title: 'About', completed: false },
          { id: 'st-2', title: 'Careers', completed: false },
        ],
        activities: [],
        commentsCount: 0,
        attachmentsCount: 0,
        order: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-2',
        title: 'Presentation for Dribbble',
        description: "Approved the design of the iOS app, let's make a presentation.",
        columnId: 'col-new',
        priority: 'urgent',
        assignees: [INITIAL_USERS[4], INITIAL_USERS[2]], // Elena, Sarah
        tags: [INITIAL_TAGS[2], INITIAL_TAGS[1]], // Dribbble, Design
        subtasks: [],
        activities: [],
        attachments: [
          { id: 'att-1', name: 'Mobile 1', url: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?w=100&auto=format&fit=crop&q=60', type: 'image' },
          { id: 'att-2', name: 'Mobile 2', url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=100&auto=format&fit=crop&q=60', type: 'image' },
          { id: 'att-3', name: 'Mobile 3', url: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=100&auto=format&fit=crop&q=60', type: 'image' },
          { id: 'att-4', name: 'Mobile 4', url: 'https://images.unsplash.com/photo-1526406915894-7bcd65f60845?w=100&auto=format&fit=crop&q=60', type: 'image' },
          { id: 'att-5', name: 'Mobile 5', url: 'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=100&auto=format&fit=crop&q=60', type: 'image' },
        ],
        commentsCount: 2,
        attachmentsCount: 14,
        order: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-3',
        title: 'Home page bugs fixes',
        description: 'I found several mistakes. Made a list, attached it below',
        columnId: 'col-new',
        priority: 'medium',
        assignees: [INITIAL_USERS[4], INITIAL_USERS[2]],
        tags: [INITIAL_TAGS[0], INITIAL_TAGS[5]], // Website, Frontend
        subtasks: [],
        activities: [],
        commentsCount: 0,
        attachmentsCount: 0,
        order: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-4',
        title: 'Secret Marketing Page',
        description: 'We need to make a page for a special offer for the most loyal customers',
        columnId: 'col-progress',
        priority: 'high',
        assignees: [INITIAL_USERS[1], INITIAL_USERS[3]], // Alex, Marcus
        tags: [INITIAL_TAGS[0], INITIAL_TAGS[1]], // Website, Design
        subtasks: [
          { id: 'st-4-1', title: 'Approved budget', completed: true },
          { id: 'st-4-2', title: 'Initial design review', completed: false },
          { id: 'st-4-3', title: 'First design concept', completed: false },
          { id: 'st-4-4', title: 'Second design concept', completed: false },
        ],
        attachments: [
          { id: 'att-6', name: 'Preview 1', url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=100&auto=format&fit=crop&q=60', type: 'image' },
          { id: 'att-7', name: 'Preview 2', url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&auto=format&fit=crop&q=60', type: 'image' },
        ],
        activities: [],
        commentsCount: 10,
        attachmentsCount: 2,
        order: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-5',
        title: 'Planning meeting for the second version of the app',
        description: '',
        columnId: 'col-progress',
        priority: 'medium',
        assignees: [INITIAL_USERS[3]], // Marcus
        tags: [INITIAL_TAGS[3], INITIAL_TAGS[6]], // App, Planning
        subtasks: [],
        activities: [],
        commentsCount: 1,
        attachmentsCount: 0,
        order: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-6',
        title: 'Second design concept',
        description: "Let's do the exact opposite of the first concept. Light theme, minimalism and lightness",
        columnId: 'col-complete',
        priority: 'medium',
        assignees: [INITIAL_USERS[3]],
        tags: [INITIAL_TAGS[0], INITIAL_TAGS[1]], // Website, Design
        subtasks: [],
        activities: [],
        commentsCount: 18,
        attachmentsCount: 2,
        order: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-7',
        title: 'Do competitor research',
        description: 'You need to research competitors and identify weaknesses and strengths each of them',
        columnId: 'col-complete',
        priority: 'high',
        assignees: [INITIAL_USERS[3], INITIAL_USERS[1]],
        tags: [INITIAL_TAGS[3], INITIAL_TAGS[4]], // App, Research
        subtasks: [],
        activities: [],
        commentsCount: 3,
        attachmentsCount: 2,
        order: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-8',
        title: 'First design concept',
        description: "Let's try a dark theme and bright colors for accents.",
        columnId: 'col-complete',
        priority: 'high',
        assignees: [INITIAL_USERS[3]],
        tags: [INITIAL_TAGS[0], INITIAL_TAGS[1]], // Website, Design
        subtasks: [],
        activities: [],
        commentsCount: 18,
        attachmentsCount: 2,
        order: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'task-9',
        title: "Let's discuss the tasks and plan the timeline",
        description: '',
        columnId: 'col-complete',
        priority: 'low',
        assignees: [],
        tags: [INITIAL_TAGS[0], INITIAL_TAGS[6]], // Website, Planning
        subtasks: [],
        activities: [],
        commentsCount: 0,
        attachmentsCount: 0,
        order: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'proj-mirage',
    name: 'Mirage',
    key: 'MRG',
    description: 'Next-gen banking interfaces',
    icon: 'Star',
    color: '#F59E0B',
    category: 'favorites',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-mashroom',
    name: 'Mashroom',
    key: 'MSH',
    description: 'Design system tokens & assets',
    icon: 'Circle',
    color: '#8B5CF6',
    category: 'favorites',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-weedo',
    name: 'Weedo',
    key: 'WDO',
    description: 'E-commerce platform',
    icon: 'Circle',
    color: '#EC4899',
    category: 'favorites',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-lonely-walls',
    name: 'Lonely Walls',
    key: 'LNW',
    description: 'Gallery and art collection app',
    icon: 'Triangle',
    color: '#10B981',
    category: 'favorites',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-essential',
    name: 'Essential Bottle',
    key: 'EBT',
    description: 'Packaging and brand design',
    icon: 'Circle',
    color: '#64748B',
    category: 'all',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-new-shtetl',
    name: 'New Shtetl',
    key: 'NST',
    description: 'Cultural archive platform',
    icon: 'Triangle',
    color: '#64748B',
    category: 'all',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-nintendo',
    name: 'Nintendo',
    key: 'NTD',
    description: 'Interactive gaming showcase',
    icon: 'Square',
    color: '#64748B',
    category: 'all',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-select',
    name: 'Select',
    key: 'SLC',
    description: 'Curated products',
    icon: 'Triangle',
    color: '#64748B',
    category: 'all',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-virgin',
    name: 'Virgin Galactic',
    key: 'VGC',
    description: 'Spaceflight dashboard',
    icon: 'Square',
    color: '#EF4444',
    badgeCount: 1,
    category: 'all',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-zephyr',
    name: 'Zephyr',
    key: 'ZPH',
    description: 'Wind energy analytics',
    icon: 'Circle',
    color: '#8B5CF6',
    category: 'all',
    members: INITIAL_USERS,
    availableTags: INITIAL_TAGS,
    columns: [],
    tasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
